### ISSUE TITLE
Curriculum planning - Ethereum

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/play#1]
# ETHEREUM WORKSHOPS

---
ABOUT:
Full stack of buidling dapps, tool is the workshop is always play editor)

TOPIC IDEAS:

    * [ ] play editor workshop
    * [ ] workshop on how to use play workshops and skilltree system
    * [ ] solidity workshop
    * [ ] javascript/html/css workshop
    * [ ] deploying (main net, test nets, shards)
    * [ ] web3/ether.js
    * [ ] metamask or other alternatives
    * [ ] (oraclize fitbit) https://github.com/ethereum/play/issues/19
    * [x] [#19 workshop (fitbit, oraclize)](https://github.com/ethereum/play/issues/19)
    * [ ] [#41 add solidity workshop](https://github.com/ethereum/play/issues/41)
    * [ ] add remix workshop https://github.com/ethereum-play/workshop-remix
    * [ ] add play-editor workshop https://github.com/ethereum-play/workshop-play-editor
    * [ ] add fitbit-dapp workshop https://github.com/ethereum-play/workshop-fitbit-dapp/issues/1
      * by turning workshop(fitbit, oraclize) into a workshop page
    * [ ] add all basic workshops (requirements) first
    * [ ] [#7 publish code camp landing github page](https://github.com/ethereum/play/issues/7)

**CONTENT:**

1. LISTS:
  * list of resources from education telegram group
https://docs.google.com/spreadsheets/d/1MdEEkeLFFyfP9SlRMHZMlPUq2Ks_H1g0FMrOZ6y942E/edit#gid=0
  *  from ailin 
https://github.com/alincode/ethereum-zero-to-hero
  * (@ mr. rigel) 
https://ethereum.network/learn
   * Github awesome lists
https://www.google.com/search?ei=htd_XOD4G9yFjLsP1qGzyAI&q=github+awesome+list+ethereum&oq=github+awesome+list+ethereum&gs_l=psy-ab.3..33i22i29i30.1296.2439..2590...0.0..0.79.621.9......0....1..gws-wiz.......0i71j0i22i30.poS4d-lH92s

2. UNSORTED:
  * https://github.com/miguelmota/solidity-idiosyncrasies
  * https://github.com/ConsenSys/smart-contract-best-practices
  * https://github.com/fivedogit/solidity-baby-steps/tree/master/contracts
  * https://solidity.readthedocs.io/en/v0.4.24/common-patterns.html
  * magicians forum
  * zero knowledge podcast (ana rose)
  * ethereum wiki
  * MIT blockchain
  * reddit ethereum & ethereum/dev
  * design for crypto.com
  * jackson palmer youtube channel
  * crypto news / mastering ethereum
  * antonopulous
  * LOPP.net/bitcoin.html
  * crypto cannon articles
  * weekly newsletter (for blockchain - nina has link)
  * social coding room (KAI-riot) ...livepeer?
  * livepeer
  * crypto zombies
  * https://ethereum-magicians.org/t/education-session-outtakes-list-of-resources/724
  * https://medium.com/crypto-nyc/twelve-reasons-im-bullish-about-ethereum-today-809a234312b2
  * Solidity series YTB: 
https://www.youtube.com/playlist?list=PL16WqdAj66SCOdL6XIFbke-XQg2GW_Avg
  * Building ICO series 
https://www.youtube.com/playlist?list=PLS5SEs8ZftgULF-lbxy-is9x_7mTMHFIN
  * Web3.js series 
https://www.youtube.com/playlist?list=PLS5SEs8ZftgXlCGXNfzKdq7nGBcIaVOdN
  * Creating an ETH token series: 
https://www.youtube.com/playlist?list=PLS5SEs8ZftgWFuKg2wbm_0GLV0Tiy1R-n
  * https://coursetro.com/posts/code/98/Smart-Contracts-and-Decentralized-Apps-101
--- 

**PARTNERS:** (we should get content from them)
* solidity team
* openZeppelin team
* Remix team
* DAOstack (Israeli on-chain governance/DAO)
* Goerli/Polkadot
* Metamask
* Burner wallet
* CryptoEconomics
* Ethers.js/Web3
* eWasm (Jake - writing contracts in Rust and running them on eWasm test net)
* ChainSafe (ethereum 2.0, goerli, polkadot, parachains, wasm interpreter, grandpa)
* ethereum.js team
* Tabookey (https://medium.com/tabookey/1-800-ethereum-gas-stations-network-for-toll-free-transactions-4bbfc03a0a56)

**Comment by ninabreznik** [comment]
https://coingape.com/how-to-start-working-with-dapp-for-students/
