### ISSUE TITLE
define process of outsourcing tasks and how to pay for it

### ISSUE THREAD

**Issue by serapath** [ethereum/play#11]
## `@todo`
* [ ] How to earn if you areca middle man (affiliation) - brainstorm incenive models
* [ ] add bounties (first manual outsourcing process, later define automated with smart contracts)
* [ ] people who want to get paid for working on tasks need to be self employed
* [ ] we want to outsource tasks to remote working self employed individuals and pay for it
* [ ] initially we might have contractors to work 8 - 15 hours per week until we switch to pure task based
* [ ] we integrate http://github.com/ethereum/financial-tools/
* [ ] we want to cater easy tasks to beginners who have never worked remote
* [ ] initially we want to prefer outsourcing paid tasks to self employed individuals from underprivileged backgrounds
    * where the average hourly payment is ~3-5 USD/h and want to at least pay double (6-10 USD/h)
* [ ] as soon as people are more experienced and want to work more regular, we want to slowly raise compensation to "western levels"

---
**check:**
* http://socialcoding.tk
* https://github.com/blockternship

**Comment by serapath** [comment]
> how to open a UK Ltd.?
what rights and duties does a director have?
what taxes to take care of?
what to include in an invoice?
@todo: document the process of paid contributions for self employed people who want to use a UK Ltd. company
