### ISSUE TITLE
2019.02.07-17:00Z - CANCELED

### ISSUE THREAD

**Issue by serapath** [ethereum/play#111]
# AGENDA - `CANCELED`
~~`location` https://meet.jit.si/play~~

## SPECIFICS:
  * [ ] `v0.0.0` @alincode [#46 fix and improve solidity compiler](https://github.com/ethereum/play/issues/46)
  * [ ] `v0.0.0` @ninabreznik [#49 smartcontract-app](https://github.com/ethereum/play/issues/49)
  * [ ] `v0.0.0` @serapath [#16 add tiling window manager](https://github.com/ethereum/play/issues/16)

## GENERAL:
  * [#6 ROADMAP](https://github.com/ethereum/play/issues/6)
  * [#3 SPECIFICATION](https://github.com/ethereum/play/issues/3)

## PROPOSAL

---

# PROTOCOL `2019.02.07-17:00Z`

#### @ninabreznik 
* ...

#### @ailincode
* ...

#### @serapath
* ...

#### about specifics
* ...

#### about proposals
* ...

#### in general
* ...

#### @ninabreznik 
* ...

#### @ailincode
* ...

#### @serapath
* ...
