### ISSUE TITLE
2019.02.21-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#113]
# AGENDA
`location` https://meet.jit.si/play

## SPECIFICS:
  * [x] `v0.0.0` @alincode [#46 fix and improve solidity compiler](https://github.com/ethereum/play/issues/46)
  * [ ] `v0.0.0` @ninabreznik [#49 smartcontract-app](https://github.com/ethereum/play/issues/49)
  * [ ] `v0.0.0` @serapath [#16 add tiling window manager](https://github.com/ethereum/play/issues/16)
  * [ ] `v1.0.0` @ookangzheng [#83 import/exports/sync user data (dat/git/...)](https://github.com/ethereum/play/issues/83)

## GENERAL:
  * [#6 ROADMAP](https://github.com/ethereum/play/issues/6)
  * [#3 SPECIFICATION](https://github.com/ethereum/play/issues/3)

## PROPOSAL

---

# PROTOCOL `2019.02.21-17:00Z`

#### @ninabreznik 
* ...

#### @ailincode
* ...

#### @ookangzheng 
* ...

#### @serapath
* ...

#### about specifics
* ...

#### about proposals
* ...

#### in general
* ...

#### @ninabreznik 
* ...

#### @ailincode
* ...

#### @ookangzheng 
* ...

#### @serapath
* ...
