### ISSUE TITLE
mockup / wireframe / ux

### ISSUE THREAD

**Issue by serapath** [ethereum/play#12]
## `@todo`
* [x] come up with an iterative concept so the first minimum viable product can be implemented while leaving space for more planned features in later iterations without breaking the UX of previous iterations
* [x] mockup for **Play editor** and **Play workshop**
* [x] visualize this in the **specification** as a "wireframe" and/or some kind of "business model canvas" diagram

---
**inspiration:**
* https://ethfiddle.com/63t9FVyF6w
* https://www.chainshot.com/blocks

## ELEMENTS

- full screen button on every element when in focus (chat, editor with preview, just editor, just preview, tasks etc.)

### EDITOR:
- Editor
- Preview
  - function names
  - input fields
    - verification of inputs (ok or error icons - on hover shows what is error)
    - types (bool/int etc.)
- Connect with Metamask link (see [etherscan](https://etherscan.io/token/0x06012c8cf97bead5deae237070f9587f8e7a266d#writeContract))
- Extras (add-ons)
  - browse all extras
  - publish extras
  - add/remove || activate/deactivate extras
  - some extras are activated by default (custom for embedded play editor, if someone teaches testing, they can by default activate testing extras)
- Settings
  - show only what is needed (based on file type and based on plugins installed)
  - compiler version (dropdown or slider)

### WORKSHOP
- workshop title 
  - above the lesson titles (above the video)
-  

### SKILLTREE:

OTHER TOOLS (Mist, Truffle, Remix, EthFiddle)
* [Truffle example](https://medium.com/@blockchain101/interacting-with-deployed-ethereum-contracts-in-truffle-39d7c7040455)
    * function categories: read from contract, transactions, events
* [EthFiddle example](https://ethfiddle.com/)

**Comment by ninabreznik** [comment]
![screenshot_2018-08-31_02-13-45](https://user-images.githubusercontent.com/1076427/44887325-ab756d80-acc3-11e8-9dda-b9ec98bbf65e.png)
![screenshot_2018-08-31_02-13-56](https://user-images.githubusercontent.com/1076427/44887327-ae705e00-acc3-11e8-8c33-512449c0aff2.png)
![screenshot_2018-08-31_02-14-07](https://user-images.githubusercontent.com/1076427/44887331-b29c7b80-acc3-11e8-8bb9-81ef44b0d227.png)
![screenshot_2018-08-31_02-14-35](https://user-images.githubusercontent.com/1076427/44887346-cea01d00-acc3-11e8-9428-2091281fde54.png)

**Comment by ninabreznik** [comment]
![screenshot_2018-09-06_03-15-01](https://user-images.githubusercontent.com/1076427/45131074-41593e80-b183-11e8-9f71-52ec0690dd50.png)

**Comment by serapath** [comment]
check https://files.gitter.im/ethereum/remix-dev/mNzG/Test-UI-v0.pdf
