### ISSUE TITLE
Build Planning Dashboard

### ISSUE THREAD

**Issue by serapath** [ethereum/play#120]
## `@todo`
* [ ]  maybe dissolve [#6 ROADMAP](https://github.com/ethereum/play/issues/6)
* [ ] maybe dissolve [#3 SPECIFICATION](https://github.com/ethereum/play/issues/3)
* [ ] [#57 ethereum/play repo](https://github.com/ethereum/play/issues/57)
  * [ ] `organisation` - update play repo https://github.com/ethereum/play
* [ ] `organisation` - introduce and practice using https://ethereum.github.io/play/
