### ISSUE TITLE
add social media preview (twitter, facebook, ...)

### ISSUE THREAD

**Issue by serapath** [ethereum/play#125]
## `@todo`
* [ ] research twitter card options
* [ ] research facebook card options
* [ ] research others (e.g. instagram, tiktok?, snapchat?, ...)
* [ ] make concept for **preview card** for different play apps
* [ ] implement facebook card
* [ ] implement twitter card

---
reading materials:
* check result https://cards-dev.twitter.com/validator
* check result https://developers.facebook.com/tools/debug/og/object/
* https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
* https://developers.facebook.com/docs/sharing/webmasters
* more https://sproutsocial.com/insights/twitter-cards-guide/
* old https://davidwalsh.name/twitter-cards

**Comment by ninabreznik** [comment]
I assigned this issue to @fionataeyang . It's not urgent, but sometime in the future it would be nice to also take care of this.

**Comment by fionataeyang** [comment]
Hey, Nina & Alex,
I don't understand about facebook card and twitter card. What is this using for? Do I need to design or just only write the content something about it? Like share card?

**Comment by fionataeyang** [comment]
Oh I think I know what it is. Will research it later. :)
