### ISSUE TITLE
add meta workshop (workshop-workshop)

### ISSUE THREAD

**Issue by serapath** [ethereum/play#127]
## `@todo:`
* [ ] **make new demo workshop** about how to make workshops
* [ ] add meta workshop to show how to create workshops
* [ ] add screenshots/slides to describe step by step what to do
* [ ] add comments to see default theme (e.g. `alert(JSON.stringify(play.defaults, 0, 2))`
* [ ] explain what the logo format needs to be
* [ ] show how to set default title prefix

---
