### ISSUE TITLE
organize codecamps

### ISSUE THREAD

**Issue by serapath** [ethereum/play#129]
## `@todo`
* [ ] codecamp december seoul (@nonce)
* [ ] organize codecamp thailand (see wizardamigos facebook)
* [ ] organize codecamp UK in october
* [ ] think about codecamp in greece/crete? ...maybe in january 2020?
* [ ] think about hackathon nigeria/lagos in 2020?
