### ISSUE TITLE
api spec for eveem to make a codepen style listing of contracts

### ISSUE THREAD

**Issue by serapath** [ethereum/play#130]
# `@todo`
* [x] mock array of ~1000 contract addresses
* [x] fetch and store X=6 of 1000 contract address data (sourcecode, ...) and cache it in indexDB
* [x] display a list of boxes on the page, each box shows address + more meta information about * [ ] contract (like title, publish date, author?, ....)
* [x] have at the top and/or bottom a NEXT and PREVIOUS and maybe (FIRST and LAST) page to show the next 6 boxes
* [x] update the url with e.g. (#page=23) so somebody can copy paste the link and get to the same page again
* [x] when you click a box, it should switch to editor view which you can click "CLOSE" to return to the list of boxes view
* [ ] in editor view it updates the url to (#page=23&address=0x3r293ur2093....)

---

* https://twitter.com/kolinko/status/1130859355815927809

**Comment by alincode** [comment]
https://etherscan.io/contractsVerified
