### ISSUE TITLE
Searchable collection page

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/play#145]
## `@todo`

* [x] concept (wireframes?, style?, content?, sections?)
* [x] styling individual card
* [x] search bar (basic + advanced search)
* [x] top menu bar
* [x] pagination

---

- we should add links to current wireframes

**Comment by ninabreznik** [comment]
@fionataeyang I updated collection-page. Feel free to pull the newest version to avoid conflicts later.

How's your working going? Let me know if you want to jump on a call...
