### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/play#146]
## `@todo`

* [ ] **concept** (wireframes?, style?, content?, sections?)
* [ ] [#148: file explorer](https://github.com/ethereum/play/issues/148)
* [ ] **input fields** in the preview (details for each data type)
  * [ ] array
  * [ ] string
  * [ ] integer
  * [ ] address
  * [ ] boolean
  * [ ] bytes
* [ ] **returns/receipt**
  * [ ]  what do we display after the transaction is completed
    * [ ] what was the function input
    * [ ] what is the return from the function 
  * [ ] how to show the status: pending/in progress, finished (success/fail)
* [ ] function types
  * [ ] how to select color for: constructor, different function types (pure, payable, non payable, view)
  * [ ] how to accordingly select same color for syntax highlighting
