### ISSUE TITLE
survey feedback issue

### ISSUE THREAD

**Issue by serapath** [ethereum/play#150]
## `@todo`
* [x] fix dns settings for smartcontract.codes
* [x] enable https
* [x] show a loading spinner and all elements of the page immediately which dont require contract data
* [x] plan a new update to facebook groups, reddit, twitter, gitter channels, etc..

---
