### ISSUE TITLE
add tiling window manager

### ISSUE THREAD

**Issue by serapath** [ethereum/play#16]
## `@todo`
* [x] fix styling bug
* [x] first draft can be non-resizable
* [x] [#52 make a dark theme for it](https://github.com/ethereum/play/issues/52)
* [x] remove left/right/both buttons
* [x] it splits the screen into `editor` (left), `contract ui` (right), `menu bar` (bottom)
* [ ] fix responsiveness

---
