### ISSUE TITLE
workshop (fitbit, oraclize)

### ISSUE THREAD

**Issue by serapath** [ethereum/play#19]
## `@todo`
* [x] [#35 fitbit presentation - change requests](https://github.com/ethereum/play/issues/35)
* [x] [#32 Prepare Fitbit Demo for Remix folks](https://github.com/ethereum/play/issues/32)
* [x] [#33 Fitbit: Presentation for distributed health](https://github.com/ethereum/play/issues/33)
* [x] [#30 Fitbit workshop: User experience (UX)](https://github.com/ethereum/play/issues/30)
* [x] [#31 Oraclize Token Encryption](https://github.com/ethereum/play/issues/31)

---
**RESULT:**
* **[PREVIEW: github.com/alincode/devon4](https://github.com/alincode/devon4)**

**It would:**
1. use fitbit's api https://dev.fitbit.com/build/reference/web-api/
2. so fitbit users can "sign up" and stake some "money/tokens" (alternatively a health insurance provider could take a small percentage of peoples monthly insurance payment and stake it)
3. and fitbit users then get personalised fitness challenges
4. ...if people achieved or over achieved those challenges, they get back what they staked OR they get back money from their health insurance provider - essentially making their insurance cheaper
5. ...if people under achieved their staked tokens or part of their monthly insurance fee goes to all the ones who achieved or over achieved :-)

THIS could be the "baseline scenario" and now we could

1. connect to the fitbit API using some kind of oracle provider service thing (and teach people how to use those)
2. build the contract
3. build the frontend (dapp)
4. write some tests
5. maybe figure out a good scenario which can be used for debugging
6. etc....

The result should be presentable in multiple short captured screencasts:
1. The resources we produce should be chunked into parts that are consumable in 5-10 minutes at most for each of the chunks
2. We can then later use those in online workshops (or documentation) for other people to learn it

the above is meant as a theme (or use case) on which we can show all the different aspects ethereum users might need to think of when using the ecosystem + we can come up with a "story line" that presents all of the remix features - and then split the presentation in small individually presentable chunks :-) ...because in the real world, people want to use existing web services and databases to either fetch some data from or write some new data to.

**Comment by serapath** [comment]
Links:
* http://www.oraclize.it/#services
* support chat: https://gitter.im/oraclize/ethereum-api
* http://docs.oraclize.it/#general-concepts-query
* https://gitter.im/oraclize/ethereum-api?at=5b69e0dbc79ebc1ae7be36c3
* https://github.com/oraclize/ethereum-examples/blob/master/solidity/computation-datasource/url-requests/UrlRequests.sol#L43-L51
* https://www.youtube.com/watch?v=v2Skr_m0J2E&feature=youtu.be

To try out:
* https://remix.oraclize.it/#plugintitle=Oraclize&pluginurl=https://remix-plugin.oraclize.it
* https://github.com/oraclize/ethereum-examples/tree/master/solidity
