### ISSUE TITLE
2018.09.18-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#28]
# AGENDA
`location` https://meet.jit.si/play
* [ ] workshops (learning resources) https://github.com/ethereum/play/issues/10
  * [x] fitbit workshop https://github.com/ethereum/play/issues/19
* [ ] version@0.0.0 https://github.com/ethereum/play/issues/1
  * [x] contract ui https://github.com/ethereum/play/issues/13
  * [x] svg play logo https://github.com/ethereum/play/issues/14
  * [x] solc-js https://github.com/ethereum/play/issues/25
  * [x] editor https://github.com/ethereum/play/issues/2
  * [x] paid external contributors https://github.com/ethereum/play/issues/29
