### ISSUE TITLE
Fitbit workshop: User experience (UX)

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/play#30]
## `@todo`
* [x] [#23 use public test chain, it need to waiting very long time to get callback.](https://github.com/ethereum/play/issues/23)
* [x] [#22 oraclize often out of gas, it is hard to test.](https://github.com/ethereum/play/issues/22)
* [x] [#35 fitbit presentation - change requests](https://github.com/ethereum/play/issues/35)

---
The goal is to code a dapp (solidity + frontend) that pulls data from a regular web API.
![welnessdapp](https://user-images.githubusercontent.com/1076427/44435494-27770380-a5a8-11e8-814b-5a1b6339d904.png)
