### ISSUE TITLE
Fitbit: Presentation for distributed health

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/play#33]
## `@todo`
* [x] prepare videos/screencasts for learners
* [x] Can you try to find "test fitbit accounts"? so that learners can sign in and use the dapp?
* [x] Could you make 1-5 minute screencast videos to explain the topics used in the dapp?
    * [x] fitbit and how to use fitbit api (get token to make requests)
    * [x] use fitbit api to get steps (javascript fetch)
    * [x] use oraclize web api (to encrypt request/token)
    * [x] use web3.js to call contract methods (e.g. send encrypted request token to contract)
    * [x] use oraclize in a solidity contract ("computational query?" and what it can do)
* [x] people can join the competition, pay the entrance fee & those who actually successfully finish split the funds amognst themselves
* [x] some sponsors can join and add funds to the pool

---
Prepare the slides

To include:

- oraclize price https://github.com/oraclize/ethereum-api/issues/10
- question of privacy (if token is sent over blockchain vs. if all the competition is hosted on centralized server, problem of trust (escrow), problem of transparency (did they pay all contestants?))
- don't replace central server with a smartcontract which has an almighty owner
  - part of workshop: improve concept of contract by thinking through edge cases
    - (e.g. does the contest happen if only one participant signs up?)

### Problem
Lack of trust in NGOs creates problems when trying to raise donations for a cause. With the use of Smart contracts we can make the flow of donations from donors to recipients transparent.

### Cause - example

**DONORS**
Help us promote a healthy lifestyle by incentivizing people to be more active in their daily life. 

**CONTESTANTS**
Win 1.000$ reward for tracking your steps every day for a month. To make it hassle-free for you to get rewarded for staying active, the smart contract automatically syncs your steps from Fitbit. It checks at the end of the month if you hit your step goal every day. If you did, you will receive the full reward, if not, your reward will be reduced by -33$ for every day you didn't manage to hit your goal.

**Comment by alincode** [comment]
https://github.com/oraclize/ethereum-api/issues/10

**Comment by ninabreznik** [comment]
##Story

**Problem**
Lack of trust in NGOs creates problems when trying to raise donations for a cause. With the use of Smart contracts we can make the flow of donations from donors to recipients transparent.

**Cause - example**
Win 1.000$ reward for tracking your steps every day for a month. To make it hassle-free for you to get rewarded for staying active, the smart contract automatically syncs your steps from Fitbit. It checks at the end of the month if you hit your step goal every day. If you did, you will receive the full reward, if not, your reward will be reduced by -33$ for every day you didn't manage to hit your goal.

**Comment by serapath** [comment]
https://github.com/ethereum/play/issues/35

**Comment by serapath** [comment]
# prepare videos/screencasts for learners
@alincode 

* [ ] Can you try to find "test fitbit accounts"? so that learners can sign in and use the dapp?
* [ ] Could you make 1-5 minute screencast videos to explain the topics used in the dapp?
    * [ ] fitbit and how to use fitbit api (get token to make requests)
    * [ ] use fitbit api to get steps (javascript fetch)
    * [ ] use oraclize web api (to encrypt request/token)
    * [ ] use web3.js to call contract methods (e.g. send encrypted request token to contract)
    * [ ] use oraclize in a solidity contract ("computational query?" and what it can do)
