### ISSUE TITLE
2018.09.25-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#34]
# AGENDA
`location` https://meet.jit.si/play
* [ ] workshops (learning resources) https://github.com/ethereum/play/issues/10
  * [ ] fitbit workshop https://github.com/ethereum/play/issues/19
* [ ] version@0.0.0 https://github.com/ethereum/play/issues/1
  * [x] contract ui https://github.com/ethereum/play/issues/13
  * [x] svg play logo https://github.com/ethereum/play/issues/14
  * [ ] tiling window manager https://github.com/ethereum/play/issues/16
