### ISSUE TITLE
fitbit presentation - change requests

### ISSUE THREAD

**Issue by serapath** [ethereum/play#35]
## `@todo`
* [x] when the user signs up, the encrypted token should be stored in the contract (it's encrypted and because it's used to get `beginStep` it's now bound to our contract, so nobody else who would copy the encrypted token could use it
* [x] the methods `kill` and `ownerWithdrawal` should be removed
  * [x] because we don't want to replace centralised servers with almighty owners
* [x] for funders, the minimum funding should be bigger than the users signup fee of 0.1
* [x] users should NEVER have to update their steps
  * [x] instead, the frontend should fetch current steps from the fitbit web api to compare it to `beginStep` to show the user his progress
* [x] when the owner closes the round, the contract should now loop over all users and use their fitbit token to get their end steps
  * [x] maybe you also need to save a `beginDate` and then compare the `endDate` to check if the average daily steps were 10.000
  * [x] the user can close the round only once, so calling the method again will not be possible so the contract can never use the encrypted token again to check step data from users
* [x] if possible - this probably expensive transaction to get all steps from all users should be either paid by the funds in the contract or the owner should be re-imbursed for this by taking that amount from the funds
* [x] when users come to the page after the round was closed, they should be able to "withdraw" their funds from the contract to get them into their metamask account

---

**Comment by alincode** [comment]
item 2, 3 done.

**Comment by alincode** [comment]
item 1 done

**Comment by serapath** [comment]
* [x] add ability to set a custom `duration` (like e.g. 5 minutes) when deploying a contract instance, but (by default it's 30 days) => owner should only be allowed to close contest rount AFTER duration is over
* [x] allow `https://alincode.github.io/fitbit-dapp#dev` to show "debug buttons"
    * e.g. beginning of all javascript checks `localStorage.debug = locatin.hash === "#dev"`
    * including a button to load a different "contract address"
* [x] when in `#dev` mode, display a button to change contract instance address, so app loads with different contract
    * similar to `https://ninabreznik.github.io/voting-ethereum-contract/`
    * source code https://github.com/ninabreznik/voting-ethereum-contract/blob/master/src/index.js#L31
* [x] switch the entire contract to `ROPSTEN` test network
* [x] display on website how much time is left until the contest can close
    * e.g. **`steps in the next ${duration} ${unit ="days"} (10.000 steps per day)`**
    * add **`The Fitbit Contest ends in ${ duration - (now - start)} ${unit}`**
* [x] display to owner a button to `"end contest"` (but if duration is not over yet `alert('wait for ' + duration - (now - start))`

**Comment by serapath** [comment]
@ninabreznik 
* [ ] Can you make a PR to update the english "wording" to improve/change some variable or function names and maybe some other text (...maybe code comments, etc...)

**Comment by alincode** [comment]
- [x] fix:  updateAllUserStep should add userAddr parameter.
