### ISSUE TITLE
 2018.10.02-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#36]
# AGENDA
`location` https://meet.jit.si/play
* [ ] workshops (learning resources) https://github.com/ethereum/play/issues/10
  * [ ] fitbit workshop https://github.com/ethereum/play/issues/19
* [ ] version@0.0.0 https://github.com/ethereum/play/issues/1
  * [ ] tiling window manager https://github.com/ethereum/play/issues/16
* [ ] version@next https://github.com/ethereum/play/issues/6
  * [ ] landing page code camp https://github.com/ethereum/play/issues/7
