### ISSUE TITLE
2018.10.30-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#40]
# AGENDA
`location` https://meet.jit.si/play
* [x] workshops (learning resources) https://github.com/ethereum/play/issues/10
  * [x] fitbit workshop https://github.com/ethereum/play/issues/19
* [ ] version@0.0.0 https://github.com/ethereum/play/issues/1
  * [ ] tiling window manager https://github.com/ethereum/play/issues/16
* [ ] version@next https://github.com/ethereum/play/issues/6
  * [ ] landing page code camp https://github.com/ethereum/play/issues/7

**Comment by serapath** [comment]
**1. smartcontract app**
https://ethereum-play.github.io/play-editor/

* solidity contract with all possible "solidity features" (e.g. all data & function types, input, etc...)
    * (to test "smartcontract app" preview module)
* each input field needs form validations
    * separate validator modules which will be required by "smartcontract app" module
* change "smartcontract app" module to generate css/html/js source
    * we can use that source to display preview in editor by pasting source into iframe (`srcdoc=...`)

**2. editor**
* syntax highlighting solidity (code mirror 5 & code mirror 6)


**3. later:**
* add "JavascriptVM" (to deploy contract locally) => talk to https://twitter.com/ricmoo

* @ninabreznik each solidity function in preview will have `"send"` button in lower left corder
* add mini-terminal below each function to log latest "return value" when executed
    * scroll up to see older "return values"
    * when clicked: the return value shows next to it
    * it shows in a expandable terminal log and it is possible to scroll up to see previous return values
    * ![smartcontract](https://user-images.githubusercontent.com/1771897/47783804-9cc72900-dcfb-11e8-9f15-b77b49ad8ecd.jpg)

**4. skilltree**
https://ninabreznik.github.io/CryptoLife/
inspired by: http://www.dungeonsanddevelopers.com/#_akl_4_Your%20Name
* skilltree module displays all workshops it can find by crawling workshop.json's and `needs`/`unlocks`
* think about how to make sure we find all workshops hosted anywhere (but keep it decentralised)
* codecamp module displays only selected set of workshops (sub-skilltrees)

* improve the edges between nodes
* display workshop icons in nodes
* etc...

**5. workshop module**
https://ninabreznik.github.io/workshop_app/
https://ninabreznik.github.io/workshop_app/workshop.json
* make it themeable
* redesign default theme (play/ethereum theme)
