### ISSUE TITLE
2018.11.06-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#42]
# AGENDA
`location` https://meet.jit.si/play
* [ ] temporary issue list https://github.com/ethereum/play/issues/41
* [ ] version@0.0.0 https://github.com/ethereum/play/issues/1
  * [ ] tiling window manager https://github.com/ethereum/play/issues/16
* [ ] version@next https://github.com/ethereum/play/issues/6
  * [ ] landing page code camp https://github.com/ethereum/play/issues/7
