### ISSUE TITLE
play-editor errors

### ISSUE THREAD

**Issue by serapath** [ethereum/play#47]
## `@todo`
* [ ] show errors in play editor line numbers with icon indicators and more details on hover
* [ ] color the line(s) where the errors are present
* [ ] maybe keep a history log of compiler events including errors and warnings
* [ ] improve error messages

---
`solidity editor` display compilation errors/warnings and other indicators
