### ISSUE TITLE
2018.11.29-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#48]
# AGENDA
`location` https://meet.jit.si/play
1. **SPECIFICS:**
  * [ ] tiling window manager https://github.com/ethereum/play/issues/16
  * [ ] fix solc-js bugs https://github.com/ethereum/play/issues/46
  * [ ] update readme https://github.com/ethereum/play/issues/9
  * [ ] landing page code camp https://github.com/ethereum/play/issues/7
2. **GENERAL:**
  * [#6 ROADMAP](https://github.com/ethereum/play/issues/6)
  * [#3 SPECIFICATION](https://github.com/ethereum/play/issues/3)
