### ISSUE TITLE
Smartcontract UI improvements (WIP)

### ISSUE THREAD

**Issue by serapath** [ethereum/play#49]
## `@todo`
* [x] input fields (auto check if input is correct)
* [x] validate inputs (params)
* [x] each solidity function in preview will have `"send"` button in lower left corner
  * [x] when clicked: the return value shows next to it
* [x] fix number input fields to display correct number within valid range in input field
* [x] send transactions & get return values (write and read from the contracts)
* [x] make all contracts from the file visible in preview (one after another, collapsed by default or as 
* [x] make deployment work
* [x] present validation feedback to user
* [x] integer input (adapt range based on type)
* [x] **bug** collapse all doesnt work
* [x] **bug** collapsing a single item leaves a dashed border instead of nothing
* [x] display time stamp next to each logged transaction
* [x] types: validation for all possible solidity types
* [x] expand/collapse fix
* [x] integer and other inputs => text preselected when clicked (in focus)
* [x] when sendTx pending (blinking or snackbar or...)
* [x] types: functions: pure, view, non-payable and payable
* [x] types: boolean inputs (unselected by default, append OK to array, when all values are selected, not when first one is selected)
* [x] output: once deployed, print outputs next to function calls (with timestamp!!)

--- 
NEXT

* [ ] implement `at address` functionality to connect/load an existing contract
* [ ] website notification
  * [ ] you need to connect to Metamask
  * [x] error messages (you need to deploy first)
  * [ ] you don't have any funds
  * [ ] you can have only one contract per file (import using url links or later file explorer)
  * [ ] show when copied!
* [ ] improve tx logs 
  * [ ] show both: sent params & returns (with types of params/return values))  
  * [ ] correctly decode the output
  * [ ] it shows in a expandable terminal log and it is possible to scroll up to see previous return values
  * [ ] offer expand/collapse of terminal after each method to see 0 or just one+scroll or all results
* [ ] types: add return values (types only)
  * [ ] update return & param values after deploy
* [ ] [#53 create receipt json file + generate html/css/js of generic dapp form for deployed contract](https://github.com/ethereum/play/issues/53)
* [ ] display current metamask address (on top right corner? like a profile)
* [ ] types: dsiplay data types with flags/labels (next to function names)
* [ ] types: make send button green when all validations for inputs pass
* [ ] types: send button with return value (real value) and type
* [ ] [#54 add network simulator](https://github.com/ethereum/play/issues/54)
* [ ] errors: fix error message for wrong values (smartcontract-app)
* [ ] errors: improve error messages
* [ ] errors: solidity-validator module (=> improve error messages)
  * <https://github.com/alincode/solidity-validator.js/blob/master/src/lib/getMessage.js>
* [ ] notify editor to highlight code when hover parts of UDapp and vice versa
* [ ] be able to toggle every (sub)portion of the form into a json editor to copy/paste rather than using input fields
* [ ] [#86 theming smartcontract-app](https://github.com/ethereum/play/issues/86)
* [ ] display return values of auto fetched free read methods by default (maybe refetch after transaction?) https://github.com/ethereum/play/issues/138
* [ ] allow to send ETH directly to any contract address - no special method/function needed in source
* [ ] add small dropdown-converter tools for input values https://simpleserialize.com/
* [ ] [#139 "dogfood" smartcontract-ui](https://github.com/ethereum/play/issues/139)
---
