### ISSUE TITLE
play editor features

### ISSUE THREAD

**Issue by serapath** [ethereum/play#50]
## `@todo`
  * [ ] feature: copy the line (shift + control + D) 
  * [ ] feature: move line (shift + control + arrows)
  * [ ] feature: find in this file/all files (control + F/ shift + control + F)
  * [ ] feature: create a string/array/object (double click and write single or double quote/open bracket, curly brace..) 
  * [ ] feature: collapsing parts of the code (long functions etc.)

---
editor candies (copy selected lines, move lines, find in this file/all files)
not IDE, but EDITOR (only ethereum editor)
