### ISSUE TITLE
Play UX and UI (design & themes)

### ISSUE THREAD

**Issue by serapath** [ethereum/play#52]
## `@todo`
* [ ] [#144: Play **brand book / design guide**](https://github.com/ethereum/play/issues/144)

* [x] [#145: **Searchable collection page**](https://github.com/ethereum/play/issues/145)

* [ ] [#146: **Editor**](https://github.com/ethereum/play/issues/146)
* [ ] [#147: **Organization/About page**](https://github.com/ethereum/play/issues/147)

---
### INSPIRATION (**`style`**)
We like:
* pixelart - maybe wizardamigos logo style can be re-used? (maybe not?)
* 80s synthwave retro design](synthwave 80s)
* blockchain design 
* **https://www.pinterest.co.uk/serapath/play/**
* [synthwave colors](https://duckduckgo.com/?q=synthwave+colors&t=lm&iar=images&iax=images&ia=images)
* [pixelart synthwave 80s retro](https://www.google.com/search?safe=strict&biw=885&bih=828&tbm=isch&sa=1&ei=tYwbXdKCIoitUtGPs6AI&q=pixelart+dailies+synthwave&oq=pixelart+dailies+synthwave&gs_l=img.3...7124.8152..8238...0.0..0.63.533.10......0....1..gws-wiz-img.DHuAbZY6sHw)
* [voxelart](https://www.google.com/search?safe=strict&biw=885&bih=828&tbm=isch&sa=1&ei=Ao0bXda9H93TgwejyLW4Bw&q=voxelart&oq=voxelart&gs_l=img.3..0i10l10.10438.10636..10779.it..0.0..0.56.104.2......0....1..gws-wiz-img.lGc1ZRRm0as)
* https://www.awwwards.com/5-old-school-web-design-trends-nobody-misses.html
* https://www.retro-synthwave.com/design/retro-design-world
* https://www.pinterest.nz/mikeh3434/design-inspiration/
* https://www.pinterest.de/chmandracchia/synthwave/
* [pinterest isometric blockchain design](https://www.pinterest.de/search/pins/?q=isometric%20blockchain%20design&rs=typed&term_meta[]=isometric%7Ctyped&term_meta[]=blockchain%7Ctyped&term_meta[]=design%7Ctyped)
* https://www.artstation.com/search?q=synthwave&sort_by=relevance
* https://dribbble.com/shots/5683458-Blockchain-Gambling-Platform

**wallpapers**
* [image search](https://duckduckgo.com/?t=lm&q=80s+tron+background+wallpaper&ia=images&iax=images&iai=http%3A%2F%2Fnatewren.com%2Fthemes%2Fwallpaper2%2Fradpack%2Fradpack_1.jpg)
* https://natewren.com/themes/wallpaper2/radpack/radpack_15.jpg
* https://natewren.com/themes/wallpaper2/radpack/radpack_1.jpg

**videos**
* **https://www.youtube.com/watch?v=EAYfJckSEN0**
* **https://www.youtube.com/watch?v=WQaH3lh-CA4**
* **https://www.youtube.com/watch?v=CqaAs_3azSs**
* https://www.youtube.com/watch?v=UbQgXeY_zi4
* https://www.youtube.com/watch?v=GBUCmMxmup0
* https://www.youtube.com/watch?v=kfoJUeyMsOE
* https://www.youtube.com/watch?v=7-tNUur2YoU
* https://www.youtube.com/watch?v=RAdX_nwXlrY
* https://www.youtube.com/watch?v=7AqTB30d-Mc
* https://www.youtube.com/watch?v=9RHFFeQ2tu4

#### INSPIRATION (`searchable listing`)
* https://glitch.com/
* https://codesandbox.io/search
* https://codesandbox.io/explore
* [https://codepen.io/search/pens?q=...](https://codepen.io/search/pens?q=&page=1&order=popularity&depth=everything)
* https://www.behance.net/
* https://dribbble.com/
* https://ethfiddle.com/recent_fiddles
* https://trendland.com/
* https://www.uplabs.com/

#### INSPIRATION (`editor`)
* https://lab.superblocks.com/
* https://codepen.io/serapath/pen/NZgOBQ
* https://codesandbox.io/s/vanilla
* https://testing.playground.aepps.com/editor

### INSPIRATION (`landingpage`)
* https://wizardamigos.com
* https://repl.it/
* https://store.google.com/us/product/stadia_founders_edition?hl=en-US
* https://dribbble.com/shots/4006478-landing-page/attachments/917370
* https://codesandbox.io/
* https://mixbytes.io/
* https://blocksoftlab.com/
* https://poa.network/
* https://www.mobilego.io/
* https://secbit.io/
* https://authio.org/
* https://cardstack.com/developers
* https://scrimba.com/
* https://ui8.net/shift-design-system
* https://nomiclabs.io/
* https://webflow.com/
* https://ddex.io/
* https://omisego.network/
* https://akomba.com/#
* https://morpheuslabs.io/
* https://shapeshift.com/

#### INSPIRATION (`playproject`)
* https://oneclickdapp.com/
* https://play.ethereum.org
* https://play.ethereum.org/editor-solidity

**Comment by serapath** [comment]
inspiration


http://letsmakegames.org/wp-content/uploads/2010/06/LMG_HexagonHeroes_banner.jpg

https://depositphotos.com/43497101/stock-illustration-modern-hexagon-design.html

---
NEW

http://lynnekenney.com/wp-content/uploads/2014/03/EncouragePlay_Logo1.jpg

https://thumbs.dreamstime.com/z/flat-design-concept-science-horizontal-banner-scientist-laboratory-workplace-scientific-research-experiment-infographics-89365366.jpg

https://thumbs.dreamstime.com/z/cute-magic-collection-unicon-rainbow-fairy-wings-stars-65592453.jpg

http://www.letsplaycolne.co.uk/wp-content/uploads/2015/09/lets-play-childrens-activity-centre-logo1.png

https://www.dreamstime.com/stock-illustration-colorful-play-box-logo-web-print-media-image85675744

https://www.dreamstime.com/modern-simple-easy-to-recognize-right-logo-design-your-company-related-music-dj-recording-etc-play-symbol-icon-image117981773

https://imgur.com/a/CJg0ADq

**Comment by ninabreznik** [comment]
We also need to define our communication/branding goals (professional?, playful?, functional?, magical?, artsy?, minimalistic?, ... -> what to focus on )

**Comment by serapath** [comment]
i like `playful sci-fi magic`, and `minimalistic` - i just don't know how to merge that :D

**Comment by fionataeyang** [comment]
Alex,
I think we can use the color of playful sci-fi magic but the style uses minimalistic. Coz these two things are conflict a lot. So, basically we can pick up the point thing to decorate it.

**Comment by fionataeyang** [comment]
I found most popular effect js that you've been showed me some website are using it.
https://vincentgarreau.com/particles.js/

I've been thinking maybe we can find some other very cool effect library to add it on the website.

**Comment by fionataeyang** [comment]
Hey, I made the inspirations on pinterest, and it's private that only ppl know the link can view the board.
https://pin.it/quf6n3n6ucexey

**Comment by serapath** [comment]
yeah, let's take some time on tuesday to go through and gather some opinons from everyone to see what are pro's and con's and what would be nice to communicate with what we choose ...and also what makes sense or what is possible in the context of the actual tool we are trying to build

**Comment by serapath** [comment]
**update** for https://playproject.io/

here is the selection from your pinterest that i think is closest to what we imagine :-)
* https://www.pinterest.de/serapath/play2/

I added some extra and below is a list of additional relevant links
* cards
    * https://glitch.com/@glitch/glitch-this-week-june-26-2019
    * https://codesandbox.io/search
    * https://codesandbox.io/explore
    * https://codepen.io/search/pens?q=wallpaper&page=1&order=popularity&depth=everything
    * **https://ethfiddle.com/recent_fiddles**
 * editors
    * https://playproject.io/editor-solidity/
    * https://lab.superblocks.com/
    * https://codesandbox.io/s/vanilla
    * https://testing.playground.aepps.com/editor
* landingpages
    * https://cardstack.com/
    * https://www.mobilego.io/
    * https://poa.network/
    * https://mixbytes.io/

and some more color schemes ...not yet sure about the exact ones
* black
* white
* https://coolors.co/aaff00-07fdfc-e706ff-ea32ff-09ffc3
* https://coolors.co/8756d9-f222ff-ff2975-00ff9f-0df3f5
* https://coolors.co/07fdfc-aa00ff-8700ff-e706ff-ff009d

**Comment by fionataeyang** [comment]
Looks very great. Thanks. I will follow these to create the concept for the editor first. And if maybe there will be enough time to concept for the search list in this week.

**Comment by ninabreznik** [comment]
Sounds great! Ping us if you need any input :)

**Comment by fionataeyang** [comment]
Hey, Alex and Nina,
This is so far that I've finished the wireframe prototype, and make the dark and white theme, also created the prototype for each themes.

I will design sign up, sign in and user profile pages.
Please give me some advices, and check the behavior of prototype if there is not suitable or need to improve that we can discuss on the meeting or leave a message on slack to me.

Wireframe prototype
https://projects.invisionapp.com/share/U9SZMK6J873#/screens/373710393_Editor_Solidity_Wireframe_-_Default

Dark theme prototype
https://projects.invisionapp.com/share/U9SZMK6J873#/screens/373710476_Editor_Solidity_-_Dark_Theme

White theme prototype
https://projects.invisionapp.com/share/U9SZMK6J873#/373710475_Editor_Solidity_-_White_Theme

**Comment by ninabreznik** [comment]
Hey, Fiona,

I like the themes for the editor. I think we should go with your suggestion and see how users will like it. I think what is also important to add is How will we show users that sending transaction is in progress (currently we have a little animation, because on blockchain executions (=transactions) are not instant, they take a bit time)... See my demo. https://www.loom.com/share/eda49b7304bf4e568b83f90d4b99a813

Also, we need to make a detailed view for each data type (string, integer, bytes, array, etc.). We should maybe have another call tomorrow before the meeting and we walk you through the editor and show you all the details that we thought through already.

I created 4 sub-issues so we can more in details discuss each part of the project.

---

I think that before going to user profiles, I would rather to back to collection page, since we'll need couple of months (more than 1/2 of a year) to have `"backend" and the rest of the app` ready for profiles page, so we are not in a hurry with this.

---

So, I think the best way to go forward would be to also make a UI/UX for collection page now and then we can slowly start with first round of implementation. I already prepared a basic collection page view with the basic logic, so after we are ready we can start brushing the html and css part (javascript part will most likely stay untouched, or we'll fix some minor issues and I will help with working on this.).

**Comment by fionataeyang** [comment]
Hi Nina,
Yes, I also tried my way to capture some of the screens on editor. The results is you see on the prototype that I added a loading icon (That would be using animation, but not sure you'd like it. :D)

Because I've done the pages very quickly, thus I think to design other page. Lol You have any plan or idea, we can discuss always. :)

I would like to know more about collection what is there need to add more or take care the details.

I'm working on the wireframes of sign in/up, we may discuss it together or choose another day to discuss it. (It's not urgency.)
