### ISSUE TITLE
create receipt json file + generate html/css/js of generic dapp form for deployed contract

### ISSUE THREAD

**Issue by serapath** [ethereum/play#53]
## `@todo`
* [x] contract preview before deploy
* [x] contract preview after deploy
* [ ] displays deployed contracts file (using deployment file)
* [ ] change "smartcontract app" module to generate css/html/js source
    * https://codepen.io/anon/pen/rQmyNr?editors=1000
    * we can use that source to display preview in editor by pasting source into iframe (`srcdoc=...`)
* [ ] auto-generate html/css/js for preview contract (e.g. user can allow others to instantiate his contracts)
* [ ] auto-generate html/css/js for deployed contract (e.g. use can publish somewhere else)
* [ ] **advanced** (think: "currying") prefill parts or all of a smartcontract function, but instead of sending transaction, generate a "curried" (=partly filled out) form for just that individual function and make it "publishable" the same as the regular smartcontract-app

---
http://ontop.team/dappi
https://oneclickdapp.com/
