### ISSUE TITLE
add network simulator

### ISSUE THREAD

**Issue by serapath** [ethereum/play#54]
## `@todo`
* [x] add deploy logic
* [x] think how to deploy contracts (javascript vm? see new project by richard moore (ethers.js) or new stuff that was developed by iuri and yann for remix)
* [x] think about the UI -> how does user trigger deploy and how does smartcontract-app (preview) change after contract is deployed)
* [x] deploy button for constructor -> make it different (add deploy title?, also border could be thicker for deploy params)
* [ ] add network simulator
  * [ ] add "JavascriptVM" (to deploy contract locally) => talk to https://twitter.com/ricmoo
  * [ ] remix simulator
* [x] ropsten/Goerli test net

---
