### ISSUE TITLE
refine & theme workshop module (+workshop.json format)

### ISSUE THREAD

**Issue by serapath** [ethereum/play#55]
## `@todo`
* [x] make play-workshop module with workshop.json format
* [x] logic for json, so we can later build the skilltree
* [x] make it themeable
* [ ] redesign default theme (play/ethereum theme)
* [ ] easily themeable
* [ ] alpha testing - first users
* [ ] add support for limited timeboxed scheduled workshops
* [x] update mechanism for existing workshops using old workshop module versions
    * [ ] https://ninabreznik.github.io/workshop_app/
    * [ ] https://ninabreznik.github.io/workshop_app/workshop.json

---
See also [mockup / wireframe issue / ux](https://github.com/ethereum/play/issues/12)
