### ISSUE TITLE
ethereum/play repo

### ISSUE THREAD

**Issue by serapath** [ethereum/play#57]
## `@todo`
* [x] ~~delete all files but `README.md`, `.github/` and `LICENSE`~~
* [x] add description + link to ethereum-play organisation
* [ ] show ROADMAP and SPEC on page
* [ ] show a list of all ecosystem modules in alphabetical order on github page
* [ ] create organisation page module for https://ethereum.github.io/play/ to display project management
* [ ] add convenience editor to consistently add/edit issues and sync with github issues via API
* [ ] add notifications about upcoming tasks/events
* [ ] sync all github issue etc... activity to file changes in a "backup" repository to have planning under version control in git
* [ ] factor out all code into seperate tool module and make a static page specifying the data in standard format, but using tool module to generate the page
    * `ethereum-play/dashboard` - to contain the tool
    * `ethereum-play/organisation` - to contain the backup of all issues, etc... activity in files/folders
    * `ethereum/play` - to use "dashboard" tool and sync to "organisation" repo, but work on github issues, etc... as "staging area" which is (can be) committed to the "organisation" repo
* [ ] make concept of how to switch data from mono `/organisation` backup repo to a module specific repo folder to make it multi repo rather than mono repo when it comes to issues
* [ ] switch from github accounts to authorise to dat backend

---
