### ISSUE TITLE
concept for devops (tests, CI, releases, ...)

### ISSUE THREAD

**Issue by ninabreznik** [ethereum/play#59]
## `@todo`
* [ ] [archive finished versions from roadmap into comment and link to github releases](https://github.com/ethereum/play/issues/68)
* [ ] define browser compatibility standard
* [ ] setup basic testing
* [ ] setup: alpha, beta & stable deployments
* [ ] optimize bundle until eventually switching to `import` https://github.com/browserify/tinyify
* [ ] addn semi-automated release process e.g. https://github.com/ethereum/remix/releases

---

**Comment by serapath** [comment]
* [ ] optimize bundle until eventually switching to `import` https://github.com/browserify/tinyify
