### ISSUE TITLE
UI - to switch the compilation versions

### ISSUE THREAD

**Issue by serapath** [ethereum/play#60]
## `@todo`
* [x] pre-select compiler version based on "pragma"
* [ ] enable switching compiler versions (maybe with a dropdown menu)
* [ ] add UI for selecting compiler version and compile button
* [ ] indicate downloaded/cached compilers (maybe with option to "download & cache all/nightly/release")

---
