### ISSUE TITLE
handle bookmarks/files

### ISSUE THREAD

**Issue by serapath** [ethereum/play#65]
## `@todo`
* [ ] bookmark internal/external files
* [ ] load and cache external files into browser storage (automatically/when clicked)
* [ ] create new file/folder
* [ ] rename/delete/move the file
* [ ] bookmark a file (save it)
* [ ] browse files or folders
* [ ] send/export (download to computer, upload to swarm, share to github, create gist, share via local network (from coworker), share link on social media, send to a person)
  * [ ] [#83 import/exports/sync user data (dat/git/...)](https://github.com/ethereum/play/issues/83)
* [ ] receive/import (from computer, from swarm/github, get through local network)

---
