### ISSUE TITLE
publish code camp landing github page

### ISSUE THREAD

**Issue by serapath** [ethereum/play#7]
## `@todo`
* [x] [#45 configure DNS](https://github.com/ethereum/play/issues/45)
* [x] add first draft for code camp landing page to https://github.com/ethereum-play/ethereum-play.github.io
* [ ] add all workshops to codecamp page
* [ ] publish play landingpage as static basic, but functional curriculum (links to workshops) page
* [ ] brush codecamp design to look awesome :-D

---
