### ISSUE TITLE
user feedback

### ISSUE THREAD

**Issue by serapath** [ethereum/play#70]
## `@todo`
* [x] [#15 support chat integration](https://github.com/ethereum/play/issues/15)
* [ ] add report a bug button
* [ ] standardize a way to get in touch with the "supply network" of components/apps/...
---
