### ISSUE TITLE
2018.12.04-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#71]
# AGENDA
`location` https://meet.jit.si/play
1. **SPECIFICS:**
  * [ ] tiling window manager https://github.com/ethereum/play/issues/16
  * [ ] fix solc-js bugs https://github.com/ethereum/play/issues/46
  * [ ] update readme https://github.com/ethereum/play/issues/9
  * [ ] landing page code camp https://github.com/ethereum/play/issues/7
2. **GENERAL:**
  * [#6 ROADMAP](https://github.com/ethereum/play/issues/6)
  * [#3 SPECIFICATION](https://github.com/ethereum/play/issues/3)

**Comment by ninabreznik** [comment]
## Dec 4 2018 Meeting - NOTES

### Previous week
**Nina:**
- brainstorming and sketching the workshop UX
- play-workshop improvements
- workshop creators in ethereum ecosystem
    - introduction to play-workshop
    - solidity codecademy style e-learning system (try out and schedule a meeting)
    - solidity technical writer - invitation to create workshops
- updating issues on the roadmap
- updating readme on the ethereum/play repo and link to ethereum-play organization

**Alex:**
- roadmap - in details (when what why)
    - workshops module
    - skilltree module
    - content
    - devops
- compiler issue
- dns settings for play.ethereum.org
- play-logo module improvements
- landing page/placeholder for the page for now (https://ethereum-play.github.io/)
- contract for Alin

**Alin:**
- tests for solc js
- first draft of a spec/format

### Todo
- add testing to the roadmap (how to have real browser tests, not node tests)
- sol js module (switch to async await)
    - api
    - output/spec/format (0.1, 0.2, 0.3, 0.4, 0.5 + 5 last versions (0.5.1, ~~0.5.0~~, 0.4.9, 0.4.8, 0.4.7 )
    - tests for new abi and format
    - adapter for each version
- support imports in Play editor (0mkara's module) https://gitter.im/ethereum/remix-dev?at=5c077fac80986419d5406c0a workshop module improvements
- get first workshop creators + create workshop about how to create a workshop
- roadmap breakdown for workshop and skilltree modules + devops etc.
