### ISSUE TITLE
2018.12.11-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#73]
# AGENDA
`location` https://meet.jit.si/play
## SPECIFICS:
  * [x] `v0.0.0` @serapath [#16 fix styling](https://github.com/ethereum/play/issues/16)
  * [ ] `v0.0.0` @serapath [#16 fix left/right/both](https://github.com/ethereum/play/issues/16)
  * [ ] `v0.0.0` @alincode [#46 fix and improve solidity compiler](https://github.com/ethereum/play/issues/46)
  * [ ] `v0.0.0` @serapath [#9 update readme](https://github.com/ethereum/play/issues/9)
  * [ ] `v0.0.0` @serapath [#7 publish code camp landing github page](https://github.com/ethereum/play/issues/7)
  * [ ] `v1.0.0` @ninabreznik [#12 update UI/UX concept/mockup/wireframe](https://github.com/ethereum/play/issues/12)
  * [ ] `v0.0.0` @serapath [#45 link workshops code camp to play.ethereum.org (update DNS)](https://github.com/ethereum/play/issues/45)
  * [ ] `v1.0.0` @ninabreznik [#55 refine & theme workshop module (+workshop.json format)](https://github.com/ethereum/play/issues/55)
  * [ ] `v0.0.0` @serapath [#72 browser first test lib + reporter](https://github.com/ethereum/play/issues/72)
  * [ ] `v3.0.0` @ninabreznik [#69 community outreach & decentralised social scaling](https://github.com/ethereum/play/issues/69)
## GENERAL:
  * [#6 ROADMAP](https://github.com/ethereum/play/issues/6)
  * [#3 SPECIFICATION](https://github.com/ethereum/play/issues/3)

## Proposals
* [x] decide about adding [#75 exercise/lesson validation (dressed as a "virtual customer" regarding the user experience)](https://github.com/ethereum/play/issues/75) to the roadmap

**Comment by serapath** [comment]
# `2018.12.11` Meeting Notes

## What did we do? (`since last meeting`)

#### @alincode 
* `v0.0.0` @alincode [#46 fix and improve solidity compiler](https://github.com/ethereum/play/issues/46)
#### @ninabreznik 
* `v1.0.0` @ninabreznik [#55 refine & theme workshop module (+workshop.json format)](https://github.com/ethereum/play/issues/55)
#### @serapath 
* `v0.0.0` @serapath [#72 browser first test lib + reporter](https://github.com/ethereum/play/issues/72)

## Decisions (`during the meeting`)
* decision about [#75 exercise/lesson validation (dressed as a "virtual customer" regarding the user experience)](https://github.com/ethereum/play/issues/75)
    * => postpone and wait for feedback from @bit-shift and decide next week

## What's next? (`until next meeting`)
#### @alincode 
* `v0.0.0` @alincode [#46 fix and improve solidity compiler](https://github.com/ethereum/play/issues/46)
#### @ninabreznik
* `v1.0.0` @ninabreznik [#12 update UI/UX concept/mockup/wireframe](https://github.com/ethereum/play/issues/12)
#### @serapath  
* `v0.0.0` @serapath [#72 browser first test lib + reporter](https://github.com/ethereum/play/issues/72)
* `v0.0.0` @serapath [#16 fix left/right/both](https://github.com/ethereum/play/issues/16)
