### ISSUE TITLE
design compile standard output format

### ISSUE THREAD

**Issue by alincode** [ethereum/play#76]
## `@todo`
* [ ] decide and specify output format
* [ ] refactor compiler to produce output format
* [ ] update existing modules to consume the new output format

---
**Is your feature request related to a problem? Please describe.**
standard output format for different solc version compiler

**Describe the solution you'd like**
1. decide the normal standard output
1. decide error standard output

**Describe alternatives you've considered**
1. make a better compiler interface

**Additional context**

**Comment by alincode** [comment]
now
```
var compilation = {
      name: name.substring(1),
      abi: abi,
      sources: sources,
      compiler: compile,
      assembly: { assembly, opcodes },
      binary: {
        bytecodes: { bytecode, runtimeBytecode },
        sourcemap: { srcmap, srcmapRuntime },
      },
      metadata: {
        ast: data.sources[''].AST,
        devdoc: metadata.output.devdoc,
        userdoc: metadata.output.userdoc,
        functionHashes,
        gasEstimates,
        analysis: {
            warnings: [],
            others: []
        }
      }
    };
```

**Comment by serapath** [comment]
yes, i think this is what i tried to do, but it would be cool to reasearch a little bit what
* [ ] `devdoc`, `userdoc`, `functionHashes`, etc... in **metadata** are about and if it makes sense.
* [ ] also if all of this exists in all compiler versions and which do not have it
* [ ] also if the new compiler (> v0.5) offer some additional data

This was my first approach to standardize the output in something that looked more sane to me :/

**Comment by alincode** [comment]
<https://solidity.readthedocs.io/en/v0.5.1/using-the-compiler.html?highlight=outputSelection>

```
    // The available output types are as follows:
    //   abi - ABI
    //   ast - AST of all source files
    //   legacyAST - legacy AST of all source files
    //   devdoc - Developer documentation (natspec)
    //   userdoc - User documentation (natspec)
    //   metadata - Metadata
    //   ir - New assembly format before desugaring
    //   evm.assembly - New assembly format after desugaring
    //   evm.legacyAssembly - Old-style assembly format in JSON
    //   evm.bytecode.object - Bytecode object
    //   evm.bytecode.opcodes - Opcodes list
    //   evm.bytecode.sourceMap - Source mapping (useful for debugging)
    //   evm.bytecode.linkReferences - Link references (if unlinked object)
    //   evm.deployedBytecode* - Deployed bytecode (has the same options as evm.bytecode)
    //   evm.methodIdentifiers - The list of function hashes
    //   evm.gasEstimates - Function gas estimates
    //   ewasm.wast - eWASM S-expressions format (not supported atm)
    //   ewasm.wasm - eWASM binary format (not supported atm)
```

```json
{ NewContract: 
    { abi: [[Object]],
     devdoc: { methods: {}},
     evm: { bytecode: [Object]},
     metadata: '{
      "compiler": {
        "version": "0.5.1+commit.c8a2cb62"
      },
      "language": "Solidity",
      "output": {
        "abi": [...],
        "devdoc": {
          "methods": {}
        },
        "userdoc": {
          "methods": {}
        }
      },
      "settings": {
        "compilationTarget": {
          "MyContract": "NewContract"
        },
        "evmVersion": "byzantium",
        "libraries": {},
        "optimizer": {
          "enabled": true,
          "runs": 200
        },
        "remappings": []
      },
      "sources": {
        "MyContract": {
          "content": "...",
          "keccak256": "0x7523c81a65abb96ce8e0947d26b8b8a55cf3cc527bf9038ece9cf293478f9428"
        }
      },
      "version": 1
    }',
     userdoc: { methods: {}}
    },
    OldLibrary: { abi: [[Object]],
      devdoc: { methods: {}},
      evm: { bytecode: [Object]},
      metadata: '',
      userdoc: { methods: {}}
    }
}
```

**Comment by alincode** [comment]
version 0.5.0 and 0.5.1 don't have

```
functionHashes
~binary.bytecodes.runtimeBytecode~
~binary.sourcemap.srcmapRuntime~
sources.sourcecode.urls
sources.sourcecode.sourcelist
```

~the ast value is missing.~
~not sure what is problems yet.~

**Comment by serapath** [comment]
I asked here https://gitter.im/ethereum/solidity-dev?at=5c0b0c524808192b03008f03
...let's see if we can get more information on this

**Comment by serapath** [comment]
Hello @chriseth 

Below we tried to answer some of the fields in questions with links to the documentation, but one comment in the documentation that gives us some headaches is:
> `This section does not apply to solcjs, not even if it is used in commandline mode.`

### our goal:
1. We would like to learn if the linked documentation below is valid for solcjs or not.
2. We would like to know how we can do certain things the cli alows by calling JS methods instead.

We identified the following sections in the documentation that talk about the compiler **input** and **output** and we would probably change the **VERSION** in the documentation to check older compiler version for their corresponding information, but we are concerned about the docs talking about the `cli` and not `solcjs` and wonder if there are more sources we could study to answer our remaining questions:

1. https://solidity.readthedocs.io/en/v0.5.1/metadata.html
2 https://solidity.readthedocs.io/en/v0.5.1/abi-spec.html
3. https://solidity.readthedocs.io/en/v0.5.1/using-the-compiler.html
4. https://solidity.readthedocs.io/en/v0.5.1/metadata.html

# Questions
1. In what way does [this input spec](https://solidity.readthedocs.io/en/v0.5.1/using-the-compiler.html?highlight=outputSelection#input-description) apply to solcjs?
    * e.g. `sources['XXX.sol'].urls`
    * e.g. `settings.remappings`


2. How do we best get all imports a contract uses so i can fetch missing contract data from url's, cache them and pass them to the compiler when using solcjs?

3. How do I get the AST now. It seems to not be part of the compile output anymore or we have to specify it somehow - AND is it possible to get the AST without compiling using maybe another module?

4. Even though the documentation has some comments about the fields listed below, they don't really describe or define the fields in ways that make them clear enough and seem to assume a lot of background knowledge. What is the format and structure and purpose of the following compiler output fields - and how do i add/change/influence it/them?
    * [x] `compilationTarget`
        * https://solidity.readthedocs.io/en/v0.5.1/using-the-compiler.html?highlight=outputSelection#target-options
    * [x] `optimizer` (.enabled, .runs)
        * https://solidity.readthedocs.io/en/v0.5.1/using-the-compiler.html?highlight=outputSelection#using-the-commandline-compiler
    * [ ] natspec
    * [ ] `devdoc`
    * [ ] `userdoc`
    * [ ] `remappings`
    * [ ] `sources.id`
    * [ ] `metadata`
    * [ ] `version` : `1`
    * [ ] `functionHashes`
    * [ ] `ewasm.wast`
    * [ ] `ewasm.wasm`
    * [ ] `binary.bytecode.runtimeBytecode`
    * [ ] `deployedBytecode`
    * [ ] `libraries`
    * [ ] `binary.sourcemap.srcmapRuntime`
    * [ ] `sources.sourcecode.urls`
    * [ ] `sources.sourcecode.sourcelist`
    * [ ] `ast` vs. `legacyAST` vs. no ast at all?
    * [ ] `metadata.useLiteralContent`
    * [ ] `ir` (new assembly format before desugaring)
    * [ ] `evm` (.assembly,.legacyAssembly.bytecode, ...)
    * [ ] `evm.linkReferences`
    * [ ] `outputSelection` **seems to be very important but it's not entirely clear how to use it**
        * to which solidity version(s) does it apply and what are all the possible values we can select? 
    * [ ] `errors[i].component`
        * what does `"general"`, `"ewasm"`, etc... mean and what are all possible values?
    * [ ] `can there be other severity levels than `"error"` and `"warning"`?
    * [ ] `methodIdentifiers`
    * [ ] `gasEstimates` external vs internal vs creation

This list is probably not exhaustive, but a good start.

**Comment by chriseth** [comment]
Some explanation how to get the AST output: https://github.com/ethereum/solidity/pull/5621

**Comment by chriseth** [comment]
Function hashes are gone, but I guess we removed them because they can be easily generated from the ABI data.

**Comment by chriseth** [comment]
gas estimates are still there: `<filename>.<ContractName>.evm.gasEstimates`

runtime bytecode is now called `deployedBytecode`. The source maps are called `sourceMap` and they are inside the bytecode object.

The source list might actually have disappeared, I'll check that here: https://github.com/ethereum/solidity/issues/5623

**Comment by chriseth** [comment]
Answers to your questions:
 - the input description you linked ( https://solidity.readthedocs.io/en/v0.5.1/using-the-compiler.html#input-description ) is the description of the input format as used by the latest soljson or by solc-js if the wrapper is used (by default)
 - use the callback mechanism to load missing sources. Note that you cannot use any async calls during the callback, so either store what is requested and call the compiler again or load in a sync way
 - ast: see above
 - the fields: Yes, it does assume some background knowledge. If you don't know what the field is about, then you can probably ignore it.

**Comment by chriseth** [comment]
It turns out the source list is there, at least the information that is needed from the source list: `sources.<sourceName>.id` is the index into the old source list, i.e. the index that is used for the source references.

**Comment by alincode** [comment]
version 0.3.6 don't have

```
sources.compilationTarget
sources.libraries
sources.remappings
sources.sourcecode
compiler.evmVersion
compiler.language
compiler.optimizer
compiler.runs
metadata.ast.attributes
metadata.ast.id
metadata.ast.src
metadata.devdoc
metadata.userdoc
```

version 0.3.5 ~ 0.3.2 don't have

```
sources.sourcelist
binary.sourcemap.srcmap
binary.sourcemap.srcmapRuntime
```

**Comment by alincode** [comment]
version v0.2.2 don't have

```
sources.compilationTarget
sources.libraries
sources.remappings
sources.sourcecode
sources.sourcelist

compiler.evmVersion
compiler.language
compiler.optimizer
compiler.runs

metadata.ast.attributes
metadata.ast.id
metadata.ast.src
metadata.devdoc
metadata.userdoc

binary.sourcemap.srcmap
binary.sourcemap.srcmapRuntime
```

**Comment by chriseth** [comment]
@alincode @serapath any reply to my comment? Also you could consider not supporting anything prior to solidity 0.5.0. What would the big benefit be?

**Comment by alincode** [comment]
@chriseth 
1. thanks, for the example, I got AST value now.
2. if "Function hashes" is easy to get from ABI, I think, it should don't put in the standard output.

other question, I still working on it. I will reply you later.

**Comment by alincode** [comment]
ast key is change.
```
0.5.x

ast.absolutePath
ast.exportedSymbols
ast.id
ast.nodeType
ast.nodes
ast.src

0.4.x

ast.attributes
ast.children
ast.id
ast.name
ast.src
```

**Comment by alincode** [comment]
@chriseth 

I am not sure what is 

```
use the callback mechanism to load missing sources. Note that you cannot use any async calls during the callback, so either store what is requested and call the compiler again or load in a sync way
```

meaning, could you give me more information?

**Comment by chriseth** [comment]
I'm talking about this one here: https://github.com/ethereum/solc-js#example-usage-with-import-callback

The `findImports` function has to return directly with the file contents and cannot use any callbacks or promises.

**Comment by serapath** [comment]
https://solidity.readthedocs.io/en/v0.5.2/using-the-compiler.html#output-description

**Comment by alincode** [comment]
@serapath 
I have a question. now, output formation is an object.

```
{
      name: ...
      abi: ...
      sources: ...
      compiler: ...
      assembly: ...
      binary: {
        bytecodes: { bytecode, runtimeBytecode },
        sourcemap: { srcmap, srcmapRuntime },
      },
      metadata: {
        ast: ...
        devdoc: ...
        userdoc: ...
        functionHashes,
        gasEstimates,
        analysis: {
            warnings: [],
            others: []
        }
      }
    }
```

but actually, 0.5.x version, maybe have many contracts. for example.

<img width="1044" alt="2019-01-29 05 05 37" src="https://user-images.githubusercontent.com/7610755/51866294-a0faf500-2383-11e9-9b5a-4e30a05b21fa.png">

so standard output format might be an array, I think.
