### ISSUE TITLE
2018.12.18-17:00Z

### ISSUE THREAD

**Issue by serapath** [ethereum/play#79]
# AGENDA
`location` https://meet.jit.si/play
## SPECIFICS:
  * [x] @serapath [#75 refine idea behind "exercise/lesson validation"](https://github.com/ethereum/play/issues/75)
  * [ ] `v0.0.0` @serapath [#16 fix left/right/both](https://github.com/ethereum/play/issues/16)
  * [ ] `v0.0.0` @alincode [#46 fix and improve solidity compiler](https://github.com/ethereum/play/issues/46)
  * [ ] `v1.0.0` @ninabreznik [#12 update UI/UX concept/mockup/wireframe](https://github.com/ethereum/play/issues/12)
  * [ ] `v0.0.0` @serapath [#72 browser first test lib + reporter](https://github.com/ethereum/play/issues/72)
  * [ ] `v1.0.0` @ninabreznik [#55 refine & theme workshop module (+workshop.json format)](https://github.com/ethereum/play/issues/55)

-

  * [ ] `v0.0.0` @serapath [#9 update readme](https://github.com/ethereum/play/issues/9)
  * [ ] `v0.0.0` @serapath [#7 publish code camp landing github page](https://github.com/ethereum/play/issues/7)
  * [ ] `v0.0.0` @serapath [#45 link workshops code camp to play.ethereum.org (update DNS)](https://github.com/ethereum/play/issues/45)
  * [ ] `v3.0.0` @ninabreznik [#69 community outreach & decentralised social scaling](https://github.com/ethereum/play/issues/69)
## GENERAL:
  * [#6 ROADMAP](https://github.com/ethereum/play/issues/6)
  * [#3 SPECIFICATION](https://github.com/ethereum/play/issues/3)

## Proposals
* [ ] ~~decide about adding [#75 exercise/lesson validation (dressed as a "virtual customer" regarding the user experience)](https://github.com/ethereum/play/issues/75) to the roadmap~~

**Comment by serapath** [comment]
# `2018.12.18` Meeting Notes

## What did we do? (`since last meeting`)
#### @alincode 
* worked on solc-js and different compiler output versions
#### @ninabreznik 
* worked on ui concept
#### @serapath 
* 

## Discussion and Decisions (`during the meeting`)
* make solc-js codebase more modular
* postpone decision about exercise/lesson-validation module to next meeting

## What's next? (`until next meeting`)
#### @alincode 
* implement `import` logic for compiler
#### @ninabreznik
* continue work on ui concept
#### @serapath  
* work on `output` standard format for compiler
