### ISSUE TITLE
make solc-js an "(un)installable" command

### ISSUE THREAD

**Issue by serapath** [ethereum/play#84]
## `@todo`
* [ ] define self-describing command metadata (params format & valid arguments (e.g. solidity versions)
* [ ] auto-generate a UI component for a command from it's descriptive metadata
* [ ] add configuration to add/remove commands from project folders and file formats
* [ ] add `solc-js` as default command to `.sol` files as an important first command and "proof of concept"

---
### goal
We need to have a way to **add** or **remove** `commands` and associate them with certain **file formats** in certain **project folders**

### context
1. The "play" project uses an editor to display and edit files of different format (e.g. ".js", ".html", ...)
2. All files belong to project folders
3. Each project can define a custom set of available commands for the available file formats
4. The file format ".sol" refers to solidity files and in ethereum related projects can be compiled for the EVM

So maybe this needs some re-thinking of:
* https://github.com/ethereum-play/play-editor/blob/master/src/play-editor.js#L49
