### ISSUE TITLE
standardise github issue format + tooling

### ISSUE THREAD

**Issue by serapath** [ethereum/play#87]
### `@todo`
* [ ] standardize github issues to describe involved code, libraries, dependencies, repositories, etc..., so that they can be parsed by an algorithm and describe all aspects of an issue
* [ ] prepare issue template
* [ ] convert issues into issue template
* [ ] make concept to derive ROADMAP and SPEC from issues automatically

---
**inspiration**
* https://github.com/ipfs/team-mgmt
* https://github.com/ipfs/team-mgmt/issues/650
* https://github.com/ipfs/team-mgmt/issues
