### ISSUE TITLE
in-browser compatible multi-repo-management tooling concept

### ISSUE THREAD

**Issue by serapath** [ethereum/play#88]
## `@todo`
* [ ] [#87 standardise github issue format + tooling](https://github.com/ethereum/play/issues/87)
* [ ] and develop a form to interact with standardized issue so that we can make sure to not break the parseability by editing the issue manually (=> essentially github issues become the "backend" for the tool)
* [ ] develop a library to checkout and parse the issue to be able to setup all code & repo's involved for development to solve the issue

---
### context
1. Every development issue is related to code in files in one or more modules (e.g. dependencies).
2. In order to solve the issue, a developer who wants to contribute needs to clone all involved repositories, solve the issue and commit and push the changes to make a pull request.

### goal
1. standardize issues to automatically be able to check out and set up all involved code and repositories in a way that a developer can start immediately with solving the issue and knowing where to look.
2. do (1.) in a way that will work inside a browser, so that it wont be necessary to use the command line
