### ISSUE TITLE
document contribution process in readme

### ISSUE THREAD

**Issue by serapath** [ethereum/play#9]
## `@todo`
* [x] how we work with github issues and pull requests
* [x] explain how to use the module
* [ ] code of conduct
* [ ] how outsourcing and getting paid for it works
* [ ] add notes about testing/CI, github page and npm module
* [ ] add project documentation, but ideally make the app self documenting

---
* inspiration1: https://github.com/datprotocol/working-group
* inspiration2: https://github.com/datprotocol/DEPs/blob/master/proposals/0001-dep-process.md
