### ISSUE TITLE
add UX logic

### ISSUE THREAD

**Issue by serapath** [ethereum/play#94]
## `@todo`
* [ ] add switching between skilltree/workshop+editor/dashboard
* [ ] add gamification (codecombat?)
* [ ] add phases like in Mailchimp
    * (e.g. create solidity contract, create frontend, manage your deployed contracts...)

---
