### ISSUE TITLE
play editor features & refinements (e.g. ".js", ".html", ".sol", ...)

### ISSUE THREAD

**Issue by serapath** [ethereum/play#95]
## `@todo`
* [x] plain design of the editor, embeddable in any style of pages/apps
* [ ] feature: red dot after line number if compiler error (+ onhover details about error)
* [ ] feature: color the lines where compiler error is

---
play editor features & refinement (e.g. SOL/JS/HTML/CSS/MD/... editor)
